# Generated by Django 5.1 on 2025-04-28 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ncalogin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="certificate_pem",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
    ]
